requirements.txt
Moving from 0.10.6 -> 0.10.8 (Minor bug fix over 0.10.7 that broke some sites)
Google groups should work with this.
=> update to pywb 0.10.8

requirements.txt
Until pywb 0.11 is released, bump the pywb dependency
to the 'clide-side-tests' development branch of pywb
which includes fixes to Wombat JS for Safari and Edge
and integration tests for Wombat.
See https://github.com/ikreymer/pywb/tree/client-side-tests
Fixes #25
Fixes #36
Fixes #39
Fixes #44
Fixes #48
Fixes #55
Fixes #59
Fixes #60
=> Temporarily bump pywb to a development branch with Safari and Edge fixes

requirements.txt
This updates pywb to the current 'via' branch in the
robertknight/pywb fork.
This includes several fixes over upstream pywb that are
noted in the requirements.txt file. There are open
upstream pull requests and passing tests for each of them.
Fixes #64
Fixes #65
=> Update pywb to tip of 'via' branch from robertknight/pywb

via/app.py
It is not possible to configure the log level of pywb, so we have to set
the log level (WARNING and higher) by using the `logging.disable`
function.
We don't need access logging from via itself, as with the new infrastructure we get the access logs from nginx.
=> Disable logging levels INFO and lower

Jenkinsfile, Makefile
This will configure Jenkins the same way we're using it for h and bouncer. Each deploy will build the docker image and push it under the `auto` tag.
=> Configure Jenkins

blocked/prefixes, blocked/template.html, tests/blocker_test.py, via/app.py, via/blocker.py
We need to be able to omit content from the via proxy if content owners request it. This is currently implemented using some rather dubious nginx rules, and needs to move into this application for the move to Skyliner.
This commit implements a WSGI middleware responsible for serving a static page for blocked content, and adds the blocked content list to the repository in a flat file.
I've also rearranged the middleware stack so that:
- we cannot accidentally block our own static content
- we do not bother doing header sanitisation on our own block page or on static content
=> Block content from a prefix blacklist

Makefile, README.md, config.yaml
* Add documentation on how to run Via without Docker and using
the client served by a local dev install.
* Add `make serve` target and `http://localhost:5000` to
no_rewrite_prefixes key in config to make it easier to run Via
with a dev server.
=> Add documentation on how to use Via with a local client and service

Dockerfile, conf/squid.conf, conf/supervisord.conf
This will allow us to not have an external squid instance running. It
still can be configured with the environment variables, both the
`HTTP_PROXY` and `HTTPS_PROXY` variables should be set to
`http://localhost:3128`.
The easiest way to test:
```
$ make docker
$ docker run -it --rm -p 9080:9080 -e HTTPS_PROXY=http://localhost:3128 -e HTTP_PROXY=http://localhost:3128 hypothesis/via:latest
```
And then in the browser go to http://localhost:9080/http://169.254.169.254/latest/meta-data/
This is the AWS metadata endpoint which we specifically block in the squid config, so you should see an "Access Denied" squid error page.
=> Run squid in docker container

uwsgi.ini
Automatically kill workers using uWSGI's "harakiri" feature [1] if they
take longer than 60 seconds to respond to a request. This fixes an issue
where workers could get stuck if making an HTTP request to an external
host which is unresponsive, eventually making the whole service
unresponsive once all 32 workers get stuck.
This will have the effect of preventing very large or very slow-loading
resources from being proxied through Via.
Also enable the Python Tracebacker [2] facility so that a stack trace
for auto-killed workers is written to uWSGI's log output. In production
this can be obtained from the Docker logs. This log output includes the
URL of the request which is useful for trying to reproduce the issue.
[1] http://uwsgi-docs.readthedocs.io/en/latest/Glossary.html?highlight=harakir …
=> Auto-kill workers if request takes longer than 60 seconds.

config.yaml
Via is currently broken in development environments _if_ you configure
your dev Via to use your dev h and client. Because the URL the client is
served from (localhost:3001) is missing from Via's no_rewrite_prefixes
Via does rewrite the client's JavaScript code and Wombat.js ends up
changing the JavaScript in a way that causes a same-origin error that
causes booting up the client to fail. (Result from user's point of view:
no sidebar appears.)
=> Fix Via in development environments

templates/banner.html
This reverts commit ee9451edfa871fcf27bb58edf53cace088ca75f3.
What ee9451ed does is cause Via to not inject the client into an HTML
page if Via is not the top-level frame. This means that using Via in an
iframe is completely broken. The LTI app
(http://github.com/hypothesis/lti) - both the current one and any future
LTI app - is entirely dependent on using Via in an iframe.
That commit was a fix for this bug
https://github.com/hypothesis/h/issues/2190 that no annotations were
showing in the sidebar when this page
http://blogs.plos.org/scicomm/2015/04/13/hello-world/ was viewed in Via.
Testing locally, after reverting the commit annotations do still show on
that page in Via. So it seems the commit is no longer necessary to work
around the bug.
@judell also reported in mid-2016 that the …
=> Revert "only inject client into top-level window"

templates/banner.html
Via used to only inject the client into the top-level window
in a tab because the client didn't handle being loaded into multiple
frames in the same tab well. 26f54033bcaea0a2b4d320b23d7aed9ccf085cf6
removed this check to enable the LTI web app to include an iframe
displaying a page proxied through Via.
It is still the case however that the client has problems on sites that
have large numbers of iframes which in turn all have the client loaded
into them (see https://github.com/hypothesis/client/issues/568).
This commit reintroduces the check but only for child iframes of the
proxied page, not the top-most proxied page itself if that is contained
inside an iframe.
I did look into whether Via can be configured not to rewrite iframe src attributes but that doesn't appear to be configurable …
=> Stop injecting client into child iframes of the proxied page

Dockerfile
The python:2.7-alpine image uses the latest major version of Alpine
Linux. When a new version of Alpine is released, changes in package
organization can break Dockerfile builds from one build of Via to the next.
In this case a "silent" update to Alpine broke collectd because the "disk"
plugin was split out into a separate package (see also [1]), causing an infinite
restart of collectd on startup which eventually filled Via's logfile.
This commit pins the Alpine major version to 3.7, which is what we use
for "h" as well. This way we'll still get security updates to 3.7.x
packages but should avoid breaking changes.
[1] https://github.com/hypothesis/h/commit/7e8047db14f6804f8ca952623cf27e9f0ccd6bcc
----
You can test this locally by building the Docker image and running with a dummy …
=> Pin Alpine Linux version and install missing collectd plugin

templates/banner.html, tests/config_extractor_test.py, via/app.py, via/config_extractor.py
Support customizing aspects of the Hypothesis client configuration for a
given request by setting "via."-prefixed query params. These params are
stripped from the WSGI environment and are not seen by the proxy.
The initial use case is to support setting the "requestConfig" and
"openSidebar" client config properties, which will be needed by our LMS
integration.
In future we could also use this mechanism as a way to set "feature
flags" for requests in order to test out server-side behavior changes.
=> Support customizing Hypothesis client config on a per-request basis

static/pdfjs/proxy.js, templates/banner.html, templates/client_config.js.jinja2, templates/pdfjs_viewer.html
**Follow up to https://github.com/hypothesis/via/pull/136**
Use the same client configuration for the PDF viewer as the HTML viewer.
This enables the "via."-prefixed parameters to work when viewing a PDF through Via.
As a side benefit this also fixes an issue where client usage on PDFs in Via was not tracked correctly in Google Analytics because the `appType` key was not set in the client config.
=> Use same client configuration for PDF and HTML viewers

tests/config_extractor_test.py, via/config_extractor.py
When a URL is fetched through Via which includes "via."-prefixed query
parameters in order to control client behavior, those client config
changes were lost if the upstream server returned a redirect to a
different location.
Resolve this by intercepting 3xx-responses in the `ConfigExtractor`
middleware and rewriting the "Location" header to append the
"via."-prefixed query params from the original URL.
Fixes https://github.com/hypothesis/via/issues/138
=> Propagate "via."-prefixed query params upon upstream redirect

tests/config_extractor_test.py
The order of query params in the formatted URL is non-deterministic, so
rewrite checks to ignore the ordering.
=> Fix flakey rewrite_location_header test

templates/index.html
This PR makes small usability improvements for the URL input field on the Via homepage following testing on iOS.
- Set the input type to "url" to disable unwanted autocorrect behavior and
trigger a virtual keyboard layout specialized for entering URLs/URL-like
strings.
This required disabling built-in form validation via "novalidate" because the
input accepts values (eg. domain names with no scheme) which are not accepted
by the browser's default validation of URL inputs.
- Autofocus the URL input field when the page loads.
- Remove "maxsize" attribute, which is not a valid input attribute.
=> Improve usability of URL input field

Dockerfile
A bug in the recently released pip 19.0.1 has broken `make docker`. Pip 19.0.2 has already been released with a fix but our Docker base image doesn't seem to have 19.0.2 yet. This is a temporary workaround.
=> Fix `make docker`

requirements.txt
Via has been broken since PyYAML 5.1 was released on 13th March (see https://github.com/yaml/pyyaml/blob/master/CHANGES). Via crashes on startup. For now pin PyYAML to the last working version.
=> Pin PyYAML to the last working version

Makefile, README.md, config.yaml, tests/config_extractor_test.py, tox.ini, via/config_extractor.py
Follow the convention in our other repositories of supporting running
the server over SSL locally if `.tlscert.pem` and `.tlskey.pem` files
are present.
uwsgi installed from PyPI does not support SSL, so instead add a
separate `make dev-ssl` command which uses gunicorn, which we already
use as the WSGI HTTP server in our other apps. This is easier than
trying to rebuild uwsgi with SSL support.
One small code change was required to support gunicorn, which is not to
rely on `REQUEST_URI` being present in the WSGI environ dict, as this is
uwsgi-specific.
=> Support running Via over SSL in development

templates/banner.html
**Summary**: When an HTML document was proxied through Via, the Hypothesis client is supposed to be injected only into the main page and not any iframes that the document contains. Sometimes this logic didn't work. If the client was injected into both the main page and iframes, this caused the page to load even more slowly and in the context of the lms app, could also cause highlights from the "Public" group in the first-party authority to show up, even though the sidebar didn't show the corresponding annotations and was logged in to an LMS user account.
----
**Full details:**
The previous method relied on Via rewriting iframe `src` locations so that
the path started with `/if_/`. However there are some circumstances in
which this does not happen, such as when creating an iframe via …
=> Avoid injecting client into iframes - second attempt

conf/supervisord.conf, requirements.in, requirements.txt, tox.ini, uwsgi.ini, via/app.py
This is a fix for https://github.com/hypothesis/product-backlog/issues/1052.
Note we are [disabling the browser agent](https://rpm.newrelic.com/accounts/1385283/browser/271975748/edit#/settings?_k=1b74hd) as it's getting injected into the page that we don't own.
The [server side configuration](https://rpm.newrelic.com/accounts/1385283/applications/271975748/settings-server-side-agent-configuration) has already been setup.
Before this is released to QA and Prod we need to configure the environment variables:
- NEW_RELIC_LICENSE_KEY
- NEW_RELIC_APP_NAME=via
=> Add New Relic monitoring

static/scripts/pdfjs-init.js
Hypothesis and PDF.js both ship with the same `Promise` polyfill from
core-js v2.6.9. When that polyfill loads, it defines or overwrites the
`Promise` global unless both `Promise` and `PromiseRejectionEvent` are
already defined. The polyfill defines `Promise` but not
`PromiseRejectionEvent`. In browsers without native `Promise` support
(eg. IE 11) this means that when Hypothesis loads, its polyfill overwrites
the one created by PDF.js earlier.
Hypothesis only polyfills the basic Promise implementation, but PDF.js
polyfills and uses methods that were added later, including `finally`.
As a result, the Hypothesis client broke the PDF.js Promise polyfill
when it loaded.
Fix the issue in the most minimal way I can think of by defining a dummy
`PromiseRejectionEvent`, so that Hypothesis will …
=> Fix errors caused by missing `Promise.prototype.finally` method in IE 11

templates/pdfjs_viewer.html
Invert the feature flag so that PDF.js v2 is used by default and
switching back to PDF.js v1 is temporarily possible by adding a
`via.features=pdfjs1` query param to the URL.
Once this change has baked for a few days and we're happy there are no
significant issues, we can remove PDF.js v1 from the codebase.
nb. This change will also affect the LMS app, regardless of the LMS app's "pdfjs2" feature flag.
=> Switch to PDF.js v2 by default

Makefile, requirements-dev.in, tox.ini
Also removed the requirements-dev.in as there is only one item (flake8)
in there. At that point it's just misdirection. I noticed other repos
don't necessarily have a requirements-dev.in, so there is precident.
=> Moving the pip-compile to tox and it's own env

Jenkinsfile, Makefile, tox.ini
1. You can just do `tox -e foo` rather than `tox -e py36-foo`
2. Use `tox -qe` rather than `tox -q -e`
3. Use `@` prefix in Makefile so make doesn't print out each command
before running it
`tox -qe py36-*` is still used for the `format` and `checkformatting`
envs because these need to run with Python 3.6 (because Black requires
Python 3) whereas everything else in Via runs with Python 2.7 which is
the Via dev env's default.
For more explanation see:
hypothesis/h#5866
=> Simplify tox commands

requirements.in, requirements.txt
This dependency was originally added to support sites that require SNI [1]
but the sites mentioned in the issue and the test page at
https://check-tls.akamaized.net seem to work without it.
This dependency in turn resulted in Via having a bunch of outdated
dependencies (eg. cryptography) which appears to be a cause of a startup
crash when running the dev server on the latest version of macOS
(the issue I encountered matched https://stackoverflow.com/questions/58563849/)
If this approach doesn't work and it turns out that ngs-httpclient is
still required, we may have to update its transitive dependencies
instead.
[1] https://github.com/hypothesis/via/issues/8
=> Remove ngs-httpclient dependency

Dockerfile, bin/fetch-blocklist, conf/supervisord.conf, tests/blocker_test.py, tox.ini, via/app.py, via/blocker.py, via/default-blocklist.txt
This PR implements a way for the Via blocklist to be updated without having to re-deploy the app, enabling us to respond quicker in the event that a domain needs to be blocked.
The dynamic blocklist works as follows:
- The Python app has been configured to read the blocklist from a text file specified via the `BLOCKLIST_PATH` env var. There is a default blocklist checked into the tree as `via/default-blocklist.txt` which serves as a reference for the file format. The file is read both on startup and when processing a request if the mtime of the file has changed since the last request. The OS's stat cache should make this check very fast when nothing has changed
- The docker container configures the blocklist path to point to a temporary file fetched from a URL specified via a …
=> Support dynamically updated blocklist

templates/client_config.js.jinja2, tests/config_extractor_test.py, via/config_extractor.py
Note: This PR must land first https://github.com/hypothesis/lms/pull/1552
Change requestConfigFromFrame from a string to an object as such:
```
requestConfigFromFrame: {
origin: <string>
ancestorLevel: <number>
},
```
This extra numerical param (ancestorLevel) informs the client which parent frame to send RCP requests to.
Test URL
http://localhost:9080/https://readthedocs.org/projects/python-packaging-user-guide/downloads/pdf/latest/?via.open_sidebar=1&amp;via.request_config_from_frame=http%3A%2F%2Flocalhost%3A8001&amp;via.config_frame_ancestor_level=2
Update:
Changed this around to be built from a single json object to make the template a bit more simple. Note this still does not resolve the XSS injection issue we have and it does not appear we have magic bullet filter we can use in …
=> Add config_frame_ancestor_level param to hypothesisConfig

tests/config_extractor_test.py, tests/configuration_test.py, via/config_extractor.py, via/configuration.py
This allows anything to be sent to 'via.client.*' and have it relayed onto the client. This is a direct copy paste job from the same code in via3.
This results in a big mess as Via already has one, but it's not worth spending a lot of time untangling this to be perfect if it just gets killed off later.
----
To test run superdev then goto:
- http://localhost:9080/http://thisisaboring.website/
- http://localhost:9080/http://thisisaboring.website/?via.open_sidebar=
- http://localhost:9080/http://thisisaboring.website/?via.open_sidebar=false  #! This opens it!
- http://localhost:9080/http://thisisaboring.website/?via.open_sidebar=False  #! This opens it!
- http://localhost:9080/http://thisisaboring.website/?via.open_sidebar=0  #! This opens it!
- …
=> 1B - Swapping in the via3 configuration extraction mechanism for programatic params
